FROM node:14-alpine AS build-stage
WORKDIR /home/dptserver01/Documents/b2b-frontend
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build


# production stage
FROM nginx:stable-alpine AS production-stage
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build-stage /home/dptserver01/Documents/b2b-frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
