FROM node:14-alpine AS build-stage
WORKDIR /working/dirtory/name/
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build


# production stage
FROM nginx:stable-alpine AS production-stage
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build-stage copy/frontend/files/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
